# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Dónde estamos
    url: regiones
    weight: 10
  - name: Prensa
    url: prensa
    weight: 20
  - name: Nuestro trabajo
    url: trabajos
    weight: 30
  - name: Equipo
    url: equipo
    weight: 40
  - name: Galería de Imágenes
    url: galeria
    weight: 50
  - name: Publicaciones
    url: publicaciones
    weight: 60
  - name: Contacto
    url: '#contacto'
    weight: 70